#!/usr/bin/perl

use strict;
use warnings;

use IPC::Run3;

while( <> ) {
    s/^\s+//;
    s/\s+$//;

    my( $stdout, $stderr );
    run3 [ 'java', '-jar', '/usr/share/java/opsin.jar' ], \$_, \$stdout, \$stderr;
    $stdout =~ s/\n$//;
    print "{ smiles => '$stdout', iupac => '$_' },\n";
}
